#spawn Categories(MONSTER, CREATURE, ... defaults..., custom pools from other mods
spawnCategories = ["MONSTER,80", "CREATURE,30", "AMBIENT,15", "AXOLOTLS,3", "UNDERGROUND_WATER_CREATURE,5", "WATER_CREATURE,12", "WATER_AMBIENT,15"]

